
export const data = [
    {
        images: [
            '/1/1.webp',
            '/1/2.webp',
            '/1/3.webp',
            '/1/4.webp',
            '/1/5.webp',
            '/1/6.webp',
            '/1/7.webp',
            '/1/8.webp',
        ]
    },
    {
        images: [
            '/2/1.webp',
            '/2/2.webp',
            '/2/3.webp',
            '/2/4.webp',
            '/2/5.webp',
            '/2/6.webp',
            '/2/7.webp',
            '/2/8.webp',
            '/2/9.webp',
            '/2/10.webp',
            '/2/11.webp',
            '/2/12.webp',
            '/2/13.webp',
            '/2/14.webp',
            '/2/15.webp',
            '/2/16.webp',
            '/2/17.webp',
            '/2/18.webp',
            '/2/19.webp',
        ]
    },
    {
        images: [
            '/3/1.webp',
            '/3/2.webp',
            '/3/3.webp',
            '/3/4.webp',
            '/3/5.webp',
            '/3/6.webp',
            '/3/7.webp',
            '/3/8.webp',
            '/3/9.webp',
            '/3/10.webp',
            '/3/11.webp',
        ]
    },
    {
        images: [
            '/4/1.webp',
            '/4/2.webp',
            '/4/3.webp',
            '/4/4.webp',
            '/4/5.webp',
            '/4/6.webp',
            '/4/7.webp',
            '/4/8.webp',
            '/4/9.webp',
            '/4/10.webp',
            '/4/11.webp',
            '/4/12.webp',
        ]
    },
];